spring:
  data:
    cassandra:
      keyspace-name: main
      username: #Client Id from the generated token
      password: #Client Secret from the generated token
      schema-action: recreate-drop-unused #CREATE_IF_NOT_EXISTS if you want to keep the data in the hosted db instance
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: inboxapp
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 25MB
      max-request-size: 30MB
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: #Client ID of GitHub
            client-secret: #Client Secret of GitHub
astra:
  db:
    id: #Database ID found on database page of https://astra.datastax.com/
    region: #region you selected while creating the database instance
    keyspace: main
    application:
      token: #Token value generated
datastax.astra:
  secure-connect-bundle: connect.zip #Download the bundle from database(inbox-app) -> Connect -> Drivers -> Select Java -> Download Bundle